### ISSUE TITLE
Computing branch length after tree inference

### ISSUE THREAD

**Issue by teng-gao** [yufengwudcs/ScisTree#2]
Dear author,

I am very interested in incorporating your method in our analysis of single-cell data. I understand that ScisTree infers a phylogeny without branch length. Is there a way to compute or approximate branch lengths using the ScisTree output?

Thanks,
Teng

**Comment by yufengwudcs** [comment]
Try: ./scistree -l <data-file>.

This option wasn't advertised because it wasn't thoroughly tested. But it should work and gives some info on branch length.

**Comment by teng-gao** [comment]
Thank you!
